# number = int(input('Enter the number: '))
# result = number + (number * 11) + (number * 111)
# print(result)
number = input('Enter the number: ')
result = int(number) + int(number * 2) + int(number * 3)
print(result)